# Generated by Django 3.2.6 on 2023-10-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com_app', '0005_rename_categories_product_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='Productcategorie',
        ),
    ]
