# Generated by Django 3.2.6 on 2023-10-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com_app', '0006_rename_categorie_product_productcategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Productcategorie',
            field=models.CharField(max_length=50),
        ),
    ]
